---
- hosts: local
  roles:
    - aliases
    - direnv
    - go
    - helm
    - helm-docs
    - jq
    - k9s
    - kafkacat
    - kind
    - kubectx
    - kubeval
    - node
    - protobuf
    - rust
    - workspace
    - yarn
    - yq
