---
- name: install
  community.general.homebrew:
    name: direnv
    state: latest

- name: version
  ansible.builtin.command: direnv version
  register: version 

- name: version information
  ansible.builtin.debug:
    msg: 
      - "{{ version.stdout }}"
  when: version.stdout is defined      
