---
- name: create workspace folder
  command: mkdir "{{lookup('env', '{{ workspace_dir_env_var }}') | default('{{ workspace_default_dir }}', True) }}"
  args:
    creates: "{{lookup('env', '{{ workspace_dir_env_var }}') | default('{{ workspace_default_dir', True) }}"
