- name: brewup
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
    create: yes
    mode: '0755'

- name: awsenv
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias awsenv='env | grep AWS'

- name: awsid
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias awsid='aws sts get-caller-identity | jq'

- name: eks-clusters
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias eks-clusters='aws eks list-clusters | jq'

- name: usage information
  ansible.builtin.debug:
    msg: 
      - "source {{ aliases_file }}"
