- name: brewup
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias brewup='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'
    create: yes

- name: foo
  ansible.builtin.lineinfile:
    path: "{{ aliases_file }}"
    line: alias foo='brew update; brew upgrade; brew prune; brew cleanup; brew doctor'

- name: usage information
  ansible.builtin.debug:
    msg: 
      - "source {{ aliases_file }}"
